/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Forum.java
 *
 * Created on 10/04/2011, 19:55:55
 */

package presentation.gui;

import java.util.Observable;
import java.util.Observer;

import domain.ClientController;
import javax.swing.DefaultListModel;

import common.forum.items.ThreadInfo;
import common.forum.items.UserInfo;
import common.network.messages.ErrorMessage;
import common.notifications.FriendAddedPostNotification;
import common.notifications.PostAddedToYourThreadNotification;
import common.notifications.ThreadChangedNotification;
import java.awt.Container;
import java.awt.Graphics;
import javax.swing.JPanel;

/**
 *
 * @author
 */
public class Forum extends javax.swing.JFrame {

    private static final long serialVersionUID = -2618735121811057973L;
    private javax.swing.JPanel _mainPanel;
    private StartWindow _start;

    ClientController controller;
    public static  DefaultListModel friendsList = new DefaultListModel();
    
    /** Creates new form Forum with main panel(forun/threads/posts) */
    public Forum(ClientController clientController, StartWindow start ) {
        controller = clientController;
        _start=start;
        setFriends();
        dispalyInitialForum( new ForumsViewPanel(controller, getStartWindow() ));
        initComponents();
        this.setSize(693,516);
        setVisible(true);
    }

    public void setMainPanel(JPanel panel){
        _mainPanel=panel;
         panel.setBounds(150, 0, 520, 470);
         this.setContentPane(panel);
         this.pack();
    }

   public void clearFriends(){
       friendsList.removeAllElements();
    }

    public void setFriends(){
        for (int i=0; i<controller.getFriendList().size(); i++  ){
                 UserInfo friend = controller.getFriendList().get(i);
                 friendsList.addElement(friend.getUserName());
        }
    }

    public static DefaultListModel getFriendsListModel() {
        return friendsList;
    }

    private  JPanel getMainPanel(){
        return _mainPanel;
    }

    private StartWindow getStartWindow(){
        return _start;
    }

    public void displayForum(JPanel panel){
        if (panel!=null){
               this.remove(getMainPanel());
               setMainPanel(panel);
               initComponents();
               this.setSize(693,516);
               setVisible(true);
        }
        else
                  setVisible(false);
    }

    public void dispalyInitialForum(JPanel panel){
        if (panel!=null){
               setMainPanel(panel);
               initComponents();
               this.setSize(693,516);
               setVisible(true);
        }
        else
                  setVisible(false);
    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jButton1 = new javax.swing.JButton();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLayeredPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Hello User !", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Kristen ITC", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N

        jButton1.setFont(new java.awt.Font("Kristen ITC", 1, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\shiran\\Desktop\\logout-icon.png")); // NOI18N
        jButton1.setText("Logout");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.setBounds(20, 410, 110, 30);
        jLayeredPane1.add(jButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLayeredPane2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "My Friends", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Kristen ITC", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N

        jList1.setFont(new java.awt.Font("Kristen ITC", 1, 14)); // NOI18N
        jList1.setModel(presentation.gui.Forum.getFriendsListModel());
        jScrollPane1.setViewportView(jList1);

        jScrollPane1.setBounds(10, 40, 110, 200);
        jLayeredPane2.add(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLayeredPane2.setBounds(10, 40, 130, 260);
        jLayeredPane1.add(jLayeredPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton2.setFont(new java.awt.Font("Kristen ITC", 1, 12)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentation/gui/Edit-Users-icon.png"))); // NOI18N
        jButton2.setText("Edit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jButton2.setBounds(20, 310, 110, 30);
        jLayeredPane1.add(jButton2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        getContentPane().add(jLayeredPane1);
        jLayeredPane1.setBounds(520, 10, 150, 460);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentation/gui/forum_img.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 680, 480);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 470, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 140, 470);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        controller.logout();
        new StartWindow(controller).setSize(546,465);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        new ManageFriends(controller, getStartWindow());
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JList jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

}
