/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Forum.java
 *
 * Created on 10/04/2011, 19:55:55
 */

package presentation.gui;

import java.util.Observable;
import java.util.Observer;

import domain.ClientController;
import javax.swing.DefaultListModel;

import presentation.gui.notifications.TempNotification;

import common.forum.items.ThreadInfo;
import common.forum.items.UserInfo;
import common.network.messages.ErrorMessage;
import common.notifications.FriendAddedPostNotification;
import common.notifications.PostAddedToYourThreadNotification;
import common.notifications.ThreadChangedNotification;

/**
 *
 * @author
 */
public class Forum extends javax.swing.JFrame implements Observer{

	private static final long serialVersionUID = -2618735121811057973L;
	
	ClientController controller;
    public static  DefaultListModel friendsList= new DefaultListModel();
    
    /** Creates new form Forum */
    public Forum(ClientController clientController) {
        controller = clientController;
        controller.addObserver(this);
        /* //TO DO - wait for this implementation by avi
       for (int i=0; i<controller.getFriend().size(); i++  ){
                 String friend = controller.getFriend().get(i);
                 friendsList.addElement(friend);
        }
         * /
         */
        setVisible(true);
        initComponents();
    }

    public static DefaultListModel  getFriendsListModel() {
        return friendsList;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane3 = new javax.swing.JLayeredPane();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jButton1 = new javax.swing.JButton();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLayeredPane3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Forum System", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Kristen ITC", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        getContentPane().add(jLayeredPane3);
        jLayeredPane3.setBounds(150, 0, 520, 470);

        jLayeredPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Hello User !", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Kristen ITC", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N

        jButton1.setFont(new java.awt.Font("Kristen ITC", 1, 10));
        jButton1.setText("Logut");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.setBounds(30, 440, 80, -1);
        jLayeredPane1.add(jButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLayeredPane2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "My Friends", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Kristen ITC", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N

        jList1.setModel(presentation.gui.Forum.getFriendsListModel());
        jScrollPane1.setViewportView(jList1);

        jScrollPane1.setBounds(10, 30, 80, 130);
        jLayeredPane2.add(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLayeredPane2.setBounds(20, 140, 100, 170);
        jLayeredPane1.add(jLayeredPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton2.setFont(new java.awt.Font("Kristen ITC", 1, 10)); // NOI18N
        jButton2.setText("Edit friends");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jButton2.setBounds(10, 360, 120, 30);
        jLayeredPane1.add(jButton2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton3.setFont(new java.awt.Font("Kristen ITC", 1, 10)); // NOI18N
        jButton3.setText("Edit profile");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jButton3.setBounds(10, 320, 120, 30);
        jLayeredPane1.add(jButton3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentation/gui/P1000317.JPG"))); // NOI18N
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jLabel2.setBounds(30, 30, 80, 100);
        jLayeredPane1.add(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        getContentPane().add(jLayeredPane1);
        jLayeredPane1.setBounds(0, 0, 140, 470);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentation/gui/forum_img.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 680, 480);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 470, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 140, 470);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        controller.logout();
        new StartWindow(controller).setSize(546,465);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         new ManageFriends(controller).setSize(550,467);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JLayeredPane jLayeredPane3;
    private javax.swing.JList jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

	@Override
    public void update(Observable o, Object arg){
    	if (null != arg) nofity(arg);
    }

	private void nofity(Object arg){
		System.err.println("notification problem..");
	}

	private void nofity(final ErrorMessage em) {
		java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            	new TempNotification(em, em.getReason());
            }
        });
	}
	
	private void nofity(final ThreadChangedNotification tcn) {

		ThreadInfo tInfo = tcn.getThreadInfo();
		
		final String msg =	"Thread " + tInfo.getThread_id() +
						" (Forum " + tInfo.get_forumId() +") : \"" +
						tInfo.getTitle() + "\" has been changed";
        
		java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            	new TempNotification(tcn, msg);
            }
        });
	}
	
	private void nofity(final FriendAddedPostNotification fapn) {

		ThreadInfo tInfo = fapn.getThreadInfo();
		UserInfo uInfo = fapn.getUserInfo();
		
		final String msg =	"Your friend " + uInfo.getUserName() +
						" added post to Thread " + tInfo.getThread_id() +
						" (Forum " + tInfo.get_forumId() +") : \"" +
						tInfo.getTitle() + "\"";
		
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            	new TempNotification(fapn, msg);
            }
        });
	}
	
	private void nofity(final PostAddedToYourThreadNotification patytn) {

		ThreadInfo tInfo = patytn.getThreadInfo();
					
		final String msg =	"Your Thread " + tInfo.getThread_id() +
						" (Forum " + tInfo.get_forumId() +") : \"" +
						tInfo.getTitle() + "\" has been changed";

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            	new TempNotification(patytn, msg);
            }
        });
	}
}
