/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AviPostPanel.java
 *
 * Created on 24/04/2011, 12:36:47
 */

package presentation.gui;

import domain.ClientController;

/**
 *
 * @author yedidim
 */
public class PostPanel extends javax.swing.JPanel {
       private ClientController _clientController;
       private String _forunId;
       private String _threadId;
       private String _post_id;
	private String _title;
	private String _body;
	private String _owner;
	private String _thread_id;
	private String _dateTime;
        private  StartWindow _start;

    /** Creates new form Post */
    public PostPanel(ClientController clientController,String forumId,String threadId, String title1,
            String body1 , String owner ,String date1,String post_id,StartWindow start) {
     this._clientController=clientController;
        this._post_id=post_id;
        this._title=title1;
        this._body=body1;
        this._owner=owner;
        this._dateTime=date1;
        this._thread_id=threadId;
        this._forunId=forumId;
        this._threadId=threadId;
        this._start=start;
        initComponents();

        author.setText(owner);
        date.setText(_dateTime);
        title.setText(title1);
        body.setText(body1);
        //TODO add if statement to check if the user is the owner of the post
        if(this.getController().getCurrentLogedInUsername().equals(this.getOwner()))
        {
           editBtm.setVisible(false);
           remove.setVisible(false);
        }
        setVisible(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JLayeredPane();
        title = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        body = new javax.swing.JTextArea();
        editBtm = new javax.swing.JButton();
        author = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        remove = new javax.swing.JButton();

        mainPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Kristen ITC", 3, 14), new java.awt.Color(255, 255, 255))); // NOI18N

        title.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                titleActionPerformed(evt);
            }
        });
        title.setBounds(30, 30, 410, 20);
        mainPanel.add(title, javax.swing.JLayeredPane.DEFAULT_LAYER);

        body.setColumns(20);
        body.setRows(5);
        jScrollPane1.setViewportView(body);

        jScrollPane1.setBounds(30, 50, 410, 230);
        mainPanel.add(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        editBtm.setText("Edit");
        editBtm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBtmActionPerformed(evt);
            }
        });
        editBtm.setBounds(60, 280, 100, 23);
        mainPanel.add(editBtm, javax.swing.JLayeredPane.DEFAULT_LAYER);

        author.setFont(new java.awt.Font("Arial", 3, 14));
        author.setForeground(new java.awt.Color(0, 0, 204));
        author.setText("authore");
        author.setBounds(30, 10, 80, 20);
        mainPanel.add(author, javax.swing.JLayeredPane.DEFAULT_LAYER);

        date.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        date.setForeground(new java.awt.Color(0, 255, 0));
        date.setText("date");
        date.setBounds(400, 10, 60, 17);
        mainPanel.add(date, javax.swing.JLayeredPane.DEFAULT_LAYER);

        remove.setText("Remove");
        remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeActionPerformed(evt);
            }
        });
        remove.setBounds(310, 280, 90, 23);
        mainPanel.add(remove, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void titleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_titleActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_titleActionPerformed

    private void editBtmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBtmActionPerformed
    
      getStart().getForum().displayForum(  new EditPostPanel(this.getController(),this.getForumId(),
                                                                                                                                       this.getThreadId(),this.getPostId(),this.getStart()));
}//GEN-LAST:event_editBtmActionPerformed

    private void removeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeActionPerformed
      this.getController().RemovePost(this.getThreadId(), this.getPostId());
      getStart().getForum().displayForum(  new PostsViewPanel(this.getController(), this.getForumId(), this.getThreadId(), this.getStart()));

    }//GEN-LAST:event_removeActionPerformed

 public ClientController getController(){
     return this._clientController;
 }
 public String  getOwner(){
     return this._owner;
 }

 public String  getForumId(){
     return this._forunId;
 }

 public String  getThreadId(){
     return this._threadId;
 }

  public String  getPostId(){
     return this._post_id;
 }


 public StartWindow  getStart(){
     return this._start;
 }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel author;
    private javax.swing.JTextArea body;
    private javax.swing.JLabel date;
    private javax.swing.JButton editBtm;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLayeredPane mainPanel;
    private javax.swing.JButton remove;
    private javax.swing.JTextField title;
    // End of variables declaration//GEN-END:variables

}
