/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TempNotification.java
 *
 * Created on 08/04/2011, 20:05:45
 */

package presentation.gui.notifications;

import common.network.messages.ErrorMessage;
import common.notifications.FriendAddedPostNotification;
import common.notifications.PostAddedToYourThreadNotification;
import common.notifications.ThreadChangedNotification;

/**
 *
 * @author Avi Digmi
 */
public class TempNotification extends javax.swing.JFrame {

	private static final long serialVersionUID = 7003889355638202664L;
	
	/** Creates new form TempNotification 
	 * @param arg 
	 * @param string */
    public TempNotification(ErrorMessage arg, String msg) {
        initComponents();
        jTextArea1.setText(msg);
        this.setVisible(true);
    }

    public TempNotification(ThreadChangedNotification tcn, String msg) {
        initComponents();
        jTextArea1.setText(msg);
        this.setVisible(true);
	}

	public TempNotification(FriendAddedPostNotification fapn, String msg) {
            initComponents();
            jTextArea1.setText(msg);
            this.setVisible(true);
	}

	public TempNotification(PostAddedToYourThreadNotification patytn, String msg) {
        initComponents();
        jTextArea1.setText(msg);
        this.setVisible(true);
	}

	/** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setResizable(false);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("This Notification is from the reason:");
        getContentPane().add(jLabel1, new java.awt.GridBagConstraints());

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(jScrollPane1, gridBagConstraints);

        jPanel2.setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(jPanel2, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TempNotification(new ErrorMessage("TEST"), "").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables

}
