/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PostsViewPanel1.java
 *
 * Created on 26/04/2011, 19:46:07
 */

package presentation.gui;
import common.forum.items.PostInfo;
import domain.ClientController;
//import domain.DemoClientController;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import javax.swing.GroupLayout.ParallelGroup;
import javax.swing.GroupLayout.SequentialGroup;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.text.View;


/**
 *
 * @author yedidim
 */
public class PostsViewPanel extends javax.swing.JPanel {

 //class fields
    private ClientController _clientController;
    private String _ForumId;
    private String _threadId;
    private  StartWindow _start;

    /** Creates new form PostViewForm */
    public PostsViewPanel(ClientController clientController,String forum_id,String thread_id,StartWindow start)  {

        this._clientController=clientController;
        this._ForumId=forum_id;
        this._threadId=thread_id;
        this._start=start;
        initComponents();

        //avi shahimov
        make1_panels();
        setVisible(true);
       // postsPanel.setVisible(true);
        //avi shaimov

    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        back = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        postsPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        newPost = new javax.swing.JButton();

        jLayeredPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Forum System", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Kristen ITC", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentation/gui/go_back.png"))); // NOI18N
        back.setBorder(null);
        back.setBorderPainted(false);
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        back.setBounds(20, 30, 40, 30);
        jLayeredPane1.add(back, javax.swing.JLayeredPane.DEFAULT_LAYER);

        postsPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        postsPanel.setFocusTraversalPolicyProvider(true);
        postsPanel.setMaximumSize(new java.awt.Dimension(1000, 1000));
        postsPanel.setPreferredSize(new java.awt.Dimension(400, 320));

        javax.swing.GroupLayout postsPanelLayout = new javax.swing.GroupLayout(postsPanel);
        postsPanel.setLayout(postsPanelLayout);
        postsPanelLayout.setHorizontalGroup(
            postsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 461, Short.MAX_VALUE)
        );
        postsPanelLayout.setVerticalGroup(
            postsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 320, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(postsPanel);

        jScrollPane1.setBounds(20, 70, 480, 270);
        jLayeredPane1.add(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel2.setFont(new java.awt.Font("Kristen ITC", 1, 14));
        jLabel2.setText("List Of Posts");
        jLabel2.setBounds(210, 50, 105, 20);
        jLayeredPane1.add(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentation/gui/forum.png"))); // NOI18N
        jLabel1.setBounds(50, 340, 128, 128);
        jLayeredPane1.add(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        newPost.setFont(new java.awt.Font("Kristen ITC", 1, 14));
        newPost.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentation/gui/Threadadd.png"))); // NOI18N
        newPost.setText("Add New Post");
        newPost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newPostActionPerformed(evt);
            }
        });
        newPost.setBounds(240, 377, 230, 50);
        jLayeredPane1.add(newPost, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 511, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed

       getStart().getForum().displayForum(new ThreadsViewPanel(this.getclientController(),this.getForum_id(),this.getStart()));
        this.setVisible(false);
}//GEN-LAST:event_backActionPerformed

    private void newPostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newPostActionPerformed

       getStart().getForum().displayForum(new NewPost(this.getclientController(), this.getForum_id(),this.getThread_id(),this.getStart()));
        this.setVisible(false);
}//GEN-LAST:event_newPostActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton newPost;
    private javax.swing.JPanel postsPanel;
    // End of variables declaration//GEN-END:variables

     public void make1_panels(){
        String title;
        String body;
        String author;
        String dateTime;
        String thread_id;
        String post_id;
         // Vector<PostInfo> posts = _clientController.getPostsList(_ForumId,_threadId);
          Vector<PostInfo> posts = this.getclientController().getPostsList(this.getForum_id(),this.getThread_id());
        List<JPanel> panels = new ArrayList<JPanel>();

        for (PostInfo post : posts) {
        title=post.get_title();
        body=post.get_body();
        author=post.getOwner().getUserName();
        dateTime=post.getDateTime();
        thread_id=Integer.toString(post.getThread_id());
        post_id=Integer.toString(post.get_post_id());
        JPanel jPanel = new PostPanel(this.getclientController(),this.getForum_id(),this.getThread_id(),title,body,author,dateTime,post_id,this.getStart());
         panels.add(jPanel);

        }

        addPanels(panels);

       this.getPostsPanel().updateUI();

    }
    /**
     * adds pannels to posts panel for view
     * @param newPanels
     */
     public void addPanels(List<JPanel> newPanels){
        //postsPanel = new javax.swing.JPanel();
        javax.swing.GroupLayout postsPanelLayout = new javax.swing.GroupLayout(this.getPostsPanel());
        this.getPostsPanel().setLayout(postsPanelLayout);

        postsPanelLayout.setHorizontalGroup(
            postsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 488, Short.MAX_VALUE)
        );

        postsPanelLayout.setVerticalGroup(
            postsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 232, Short.MAX_VALUE)
        );


        ParallelGroup group1 = postsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING);

        for (JPanel jPanel : newPanels) {
                group1.addComponent(jPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE);
        }

        postsPanelLayout.setHorizontalGroup(
           postsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(postsPanelLayout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addGroup(group1)
                .addContainerGap(167, Short.MAX_VALUE))
        );

        SequentialGroup group2 =postsPanelLayout.createSequentialGroup();

        for (JPanel jPanel : newPanels) {

            group2.addComponent(jPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE);
        }

        postsPanelLayout.setVerticalGroup(
        postsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(group2.addContainerGap(25, Short.MAX_VALUE))
        );

       // pack();

    }


       //******************************************* GETTERS ************************************************//
    public ClientController getclientController(){
        return this._clientController;
    }
    public String getForum_id(){
        return this._ForumId;
    }
    public String getThread_id(){
        return this._threadId;
    }
     public JPanel getPostsPanel(){
         return postsPanel;
     }

     public  StartWindow getStart(){
         return this._start;
     }


       /**
    * @param args the command line arguments
    */
/* public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PostsViewPanel(new DemoClientController(),"1","2");
            }
        });
    }*/

}
